// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCea7lnkCGzQIz2hdWQt_UtL2b0xnmDrkE',
    appId: '1:106575691151:web:c2703a13470ca103675ffa',
    messagingSenderId: '106575691151',
    projectId: 'eos-chatting-93b04',
    authDomain: 'eos-chatting-93b04.firebaseapp.com',
    storageBucket: 'eos-chatting-93b04.appspot.com',
    measurementId: 'G-HN4PMCM2GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9KRLZjBpppXOdCHE5m6TDkRFs27toCwY',
    appId: '1:106575691151:android:d3b1cda4f611f6f8675ffa',
    messagingSenderId: '106575691151',
    projectId: 'eos-chatting-93b04',
    storageBucket: 'eos-chatting-93b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBvRB96YHD-Keo3L6pFIu_FHoVp-bNaXQ',
    appId: '1:106575691151:ios:4a46c5efe003514a675ffa',
    messagingSenderId: '106575691151',
    projectId: 'eos-chatting-93b04',
    storageBucket: 'eos-chatting-93b04.appspot.com',
    iosClientId: '106575691151-qftg8n62uiu9khn5ta13ionsdblu0cfo.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBvRB96YHD-Keo3L6pFIu_FHoVp-bNaXQ',
    appId: '1:106575691151:ios:4a46c5efe003514a675ffa',
    messagingSenderId: '106575691151',
    projectId: 'eos-chatting-93b04',
    storageBucket: 'eos-chatting-93b04.appspot.com',
    iosClientId: '106575691151-qftg8n62uiu9khn5ta13ionsdblu0cfo.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
